const professors=[{name:'Dr. Jennifer Smith',course:'Data Structures',rating:4.8,reviews:245,tag:'Excellent',dept:'Computer Science'},{name:'Prof. Michael Brown',course:'Calculus I',rating:4.7,reviews:189,tag:'Clear',dept:'Mathematics'},{name:'Dr. Sarah Johnson',course:'Psychology 101',rating:4.6,reviews:210,tag:'Helpful',dept:'Psychology'},{name:'Prof. David Lee',course:'Economics',rating:4.5,reviews:162,tag:'Fair',dept:'Economics'},{name:'Dr. Emily Carter',course:'Operating Systems',rating:4.8,reviews:137,tag:'Engaging',dept:'Computer Science'},{name:'Prof. Daniel Wilson',course:'Statistics',rating:4.7,reviews:118,tag:'Supportive',dept:'Mathematics'}];
const profGrid=document.getElementById('profGrid');const directoryGrid=document.getElementById('directoryGrid');
function initials(name){return name.split(' ').filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase()}
function card(p){return `<article class="prof-card"><div class="prof-top"><div class="prof-photo">${initials(p.name)}</div><div><h3>${p.name}</h3><small>${p.course}</small></div></div><div class="rating">★ ${p.rating} <span>(${p.reviews} reviews)</span></div><span class="tag">${p.tag}</span><p class="prof-dept">${p.dept} Department</p></article>`}
function render(list,el){el.innerHTML=list.map(card).join('')}
render(professors.slice(0,4),profGrid);render(professors,directoryGrid);
const menuBtn=document.getElementById('menuBtn');const navLinks=document.getElementById('navLinks');menuBtn.addEventListener('click',()=>navLinks.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const modal=document.getElementById('authModal');const authForm=document.getElementById('authForm');
function openAuth(mode='login'){modal.classList.add('open',mode==='signup'?'signup':'login');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.getElementById('authSubmit').textContent=mode==='signup'?'Sign Up':'Log In';document.getElementById('switchAuth').innerHTML=mode==='signup'?`Already have an account? <button data-auth="login">Log in</button>`:`Don't have an account? <button data-auth="signup">Sign up</button>`;document.querySelectorAll('#switchAuth [data-auth]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.auth)))}
function closeAuth(){modal.classList.remove('open','signup','login');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('[data-auth]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.auth)));document.querySelectorAll('[data-close="modal"]').forEach(b=>b.addEventListener('click',closeAuth));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAuth()});
authForm.addEventListener('submit',e=>{e.preventDefault();const signup=modal.classList.contains('signup');if(signup&&document.getElementById('password').value!==document.getElementById('confirmPassword').value){alert('Passwords do not match.');return}alert(signup?'Account creation UI is ready. Connect this form to your authentication backend.':'Login UI is ready. Connect this form to your authentication backend.');closeAuth();});
document.getElementById('heroSearch').addEventListener('submit',e=>{e.preventDefault();const q=document.getElementById('heroQuery').value.trim();document.getElementById('directorySearch').value=q;document.getElementById('directory').scrollIntoView({behavior:'smooth'});filterDirectory()});
const directorySearch=document.getElementById('directorySearch');const ratingFilter=document.getElementById('ratingFilter');function filterDirectory(){const q=directorySearch.value.toLowerCase();const min=Number(ratingFilter.value);const list=professors.filter(p=>(p.name.toLowerCase().includes(q)||p.course.toLowerCase().includes(q)||p.dept.toLowerCase().includes(q))&&p.rating>=min);render(list,directoryGrid)}directorySearch.addEventListener('input',filterDirectory);ratingFilter.addEventListener('change',filterDirectory);
document.querySelectorAll('.trending button').forEach(b=>b.addEventListener('click',()=>{document.getElementById('heroQuery').value=b.textContent;document.getElementById('heroSearch').dispatchEvent(new Event('submit'))}));document.getElementById('year').textContent=new Date().getFullYear();
