import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import mongoose from 'mongoose';
import { User, Professor, Review } from './models.js';
import { professorInsights, moderateReview, aiSearch, recommend, chat } from './ai.js';

const app=express(); const PORT=Number(process.env.PORT||5000); const JWT_SECRET=process.env.JWT_SECRET; const CLIENT_URL=process.env.CLIENT_URL||'*';
if(!JWT_SECRET) throw new Error('JWT_SECRET is required.'); if(!process.env.MONGODB_URI) throw new Error('MONGODB_URI is required.');
const allowedOrigins=CLIENT_URL.split(',').map(v=>v.trim()).filter(Boolean); app.disable('x-powered-by'); app.set('trust proxy',1); app.use(helmet());
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.includes('*')||allowedOrigins.includes(origin))return cb(null,true);cb(new Error('CORS origin not allowed.'));},credentials:true}));
app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:false,limit:'100kb'})); app.use('/api',rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:'draft-8',legacyHeaders:false}));
const authLimiter=rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:'draft-8',legacyHeaders:false}); const asyncRoute=h=>(req,res,next)=>Promise.resolve(h(req,res,next)).catch(next);
const publicUser=u=>({id:u._id,name:u.name,email:u.email,university:u.university,role:u.role});
function signToken(u){return jwt.sign({id:u._id.toString(),email:u.email},JWT_SECRET,{expiresIn:'7d'});} function auth(req,res,next){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({message:'Authentication required.'});try{req.user=jwt.verify(t,JWT_SECRET);next();}catch{return res.status(401).json({message:'Invalid or expired token.'});}}
async function adminAuth(req,res,next){auth(req,res,async()=>{try{const u=await User.findById(req.user.id);if(!u||u.role!=='admin')return res.status(403).json({message:'Admin access required.'});req.admin=u;next();}catch(e){next(e);}});}
const validRating=v=>{const n=Number(v);return Number.isFinite(n)&&n>=1&&n<=5;};
async function refreshProfessorStats(id){const s=await Review.aggregate([{$match:{professor:new mongoose.Types.ObjectId(id)}},{$group:{_id:null,avg:{$avg:'$rating'},count:{$sum:1}}}]);const rating=Number((s[0]?.avg||0).toFixed(1));const reviews=s[0]?.count||0;const tag=reviews===0?'New':rating>=4.7?'Excellent':rating>=4.3?'Recommended':rating>=3.5?'Good':'Mixed';await Professor.findByIdAndUpdate(id,{rating,reviews,tag});return{rating,reviews,tag};}

app.get('/',(req,res)=>res.json({service:'Professor Review Hub API',status:'running',assistant:'Sidd AI',health:'/api/health'}));
app.get('/api/health',(req,res)=>res.json({ok:mongoose.connection.readyState===1,service:'Professor Review Hub API',assistant:'Sidd AI',database:mongoose.connection.readyState===1?'connected':'disconnected',timestamp:new Date().toISOString()}));
app.post('/api/auth/register',authLimiter,asyncRoute(async(req,res)=>{const{name,email,password,university=''}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required.'});if(String(password).length<6)return res.status(400).json({message:'Password must be at least 6 characters.'});const normalized=String(email).trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(normalized))return res.status(400).json({message:'Enter a valid email address.'});if(await User.exists({email:normalized}))return res.status(409).json({message:'An account with this email already exists.'});const passwordHash=await bcrypt.hash(password,12);const user=await User.create({name:String(name).trim(),email:normalized,university:String(university).trim(),passwordHash,role:'student'});res.status(201).json({token:signToken(user),user:publicUser(user)});}));
app.post('/api/auth/login',authLimiter,asyncRoute(async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');const user=await User.findOne({email});if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({message:'Invalid email or password.'});res.json({token:signToken(user),user:publicUser(user)});}));
app.get('/api/auth/me',auth,asyncRoute(async(req,res)=>{const u=await User.findById(req.user.id).select('-passwordHash');if(!u)return res.status(404).json({message:'User not found.'});res.json({user:u});}));

app.get('/api/professors/stats/summary',asyncRoute(async(req,res)=>{const[p,r,u,a]=await Promise.all([Professor.countDocuments(),Review.countDocuments(),User.countDocuments(),Review.aggregate([{$group:{_id:null,avg:{$avg:'$rating'}}}])]);res.json({professors:p,reviews:r,users:u,averageRating:Number((a[0]?.avg||0).toFixed(1))});}));
app.get('/api/professors',asyncRoute(async(req,res)=>{const q=String(req.query.q||'').trim(),min=Math.max(0,Math.min(5,Number(req.query.minRating||0)));const filter={rating:{$gte:Number.isFinite(min)?min:0}};if(q)filter.$or=[{name:{$regex:q,$options:'i'}},{course:{$regex:q,$options:'i'}},{dept:{$regex:q,$options:'i'}},{university:{$regex:q,$options:'i'}}];const professors=await Professor.find(filter).sort({rating:-1,reviews:-1,name:1}).limit(50).lean();res.json({professors,pagination:{page:1,limit:50,total:professors.length,pages:1}});}));
app.get('/api/professors/:id',asyncRoute(async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return res.status(400).json({message:'Invalid professor ID.'});const professor=await Professor.findById(req.params.id).lean();if(!professor)return res.status(404).json({message:'Professor not found.'});const reviews=await Review.find({professor:professor._id}).populate('user','name university').sort({createdAt:-1}).lean();res.json({professor,reviews});}));

app.get('/api/reviews/professor/:id',asyncRoute(async(req,res)=>{const reviews=await Review.find({professor:req.params.id}).populate('user','name university').sort({createdAt:-1}).lean();res.json({reviews});}));
app.get('/api/reviews/mine',auth,asyncRoute(async(req,res)=>{const reviews=await Review.find({user:req.user.id}).populate('professor','name course university rating').sort({createdAt:-1}).lean();res.json({reviews});}));
app.post('/api/reviews',auth,asyncRoute(async(req,res)=>{const{professorId,rating,teachingQuality,difficulty,comment}=req.body;if(!mongoose.isValidObjectId(professorId)||![rating,teachingQuality,difficulty].every(validRating)||typeof comment!=='string'||comment.trim().length<3)return res.status(400).json({message:'Please provide valid professor, ratings and review text.'});if(!await Professor.exists({_id:professorId}))return res.status(404).json({message:'Professor not found.'});const moderation=await moderateReview(comment.trim());if(moderation.allowed===false)return res.status(422).json({message:`Sidd AI moderation: ${moderation.reason||'This review cannot be published.'}`,moderation});try{const review=await Review.create({professor:professorId,user:req.user.id,rating:Number(rating),teachingQuality:Number(teachingQuality),difficulty:Number(difficulty),comment:comment.trim(),aiSentiment:moderation.sentiment||'unknown',aiSentimentScore:Number(moderation.sentimentScore||0),aiTags:Array.isArray(moderation.tags)?moderation.tags.slice(0,8):[],aiModeration:'approved',aiModerationReason:moderation.reason||''});const professorStats=await refreshProfessorStats(professorId);const populated=await Review.findById(review._id).populate('user','name university').lean();res.status(201).json({review:populated,professorStats});}catch(e){if(e?.code===11000)return res.status(409).json({message:'You have already reviewed this professor.'});throw e;}}));
app.patch('/api/reviews/:id',auth,asyncRoute(async(req,res)=>{const updates={};for(const f of['rating','teachingQuality','difficulty'])if(req.body[f]!==undefined){if(!validRating(req.body[f]))return res.status(400).json({message:`${f} must be between 1 and 5.`});updates[f]=Number(req.body[f]);}if(req.body.comment!==undefined){if(typeof req.body.comment!=='string'||req.body.comment.trim().length<3)return res.status(400).json({message:'Comment is too short.'});updates.comment=req.body.comment.trim();}const review=await Review.findOneAndUpdate({_id:req.params.id,user:req.user.id},updates,{new:true,runValidators:true}).populate('user','name university');if(!review)return res.status(404).json({message:'Review not found.'});res.json({review,professorStats:await refreshProfessorStats(review.professor)});}));
app.delete('/api/reviews/:id',auth,asyncRoute(async(req,res)=>{const review=await Review.findOneAndDelete({_id:req.params.id,user:req.user.id});if(!review)return res.status(404).json({message:'Review not found.'});res.json({message:'Review deleted.',professorStats:await refreshProfessorStats(review.professor)});}));

// Sidd AI endpoints
app.get('/api/ai/professor/:id/insights',asyncRoute(async(req,res)=>res.json(await professorInsights(req.params.id))));
app.post('/api/ai/chat',asyncRoute(async(req,res)=>{const message=String(req.body.message||'').trim();if(!message)return res.status(400).json({message:'Ask Sidd AI a question.'});res.json({assistant:'Sidd AI',answer:await chat(message)});}));
app.post('/api/ai/search',asyncRoute(async(req,res)=>{const query=String(req.body.query||'').trim();if(!query)return res.status(400).json({message:'Search query is required.'});res.json({query,professors:await aiSearch(query)});}));
app.post('/api/ai/recommend',asyncRoute(async(req,res)=>res.json({assistant:'Sidd AI',...(await recommend(req.body||{}))})));
app.post('/api/ai/moderate',auth,asyncRoute(async(req,res)=>{const comment=String(req.body.comment||'').trim();if(!comment)return res.status(400).json({message:'Comment is required.'});res.json(await moderateReview(comment));}));

app.get('/api/admin/me',adminAuth,(req,res)=>res.json({user:publicUser(req.admin)}));
app.get('/api/admin/stats',adminAuth,asyncRoute(async(req,res)=>{const[users,admins,professors,reviews]=await Promise.all([User.countDocuments(),User.countDocuments({role:'admin'}),Professor.countDocuments(),Review.countDocuments()]);res.json({users,admins,professors,reviews});}));
app.get('/api/admin/reviews',adminAuth,asyncRoute(async(req,res)=>res.json({reviews:await Review.find().populate('user','name email university').populate('professor','name course university').sort({createdAt:-1}).limit(300).lean()})));
app.delete('/api/admin/reviews/:id',adminAuth,asyncRoute(async(req,res)=>{const r=await Review.findByIdAndDelete(req.params.id);if(!r)return res.status(404).json({message:'Review not found.'});await refreshProfessorStats(r.professor);res.json({message:'Review removed.'});}));

app.use((req,res)=>res.status(404).json({message:'API route not found.'}));
app.use((err,req,res,next)=>{console.error(err);if(err.message==='CORS origin not allowed.')return res.status(403).json({message:err.message});res.status(err.status||500).json({message:err.message||'Server error. Please try again.'});});

export async function connectDatabase(){if(mongoose.connection.readyState===1)return;await mongoose.connect(process.env.MONGODB_URI);await Promise.all([User.init(),Professor.init(),Review.init()]);await ensureAdminUser();console.log('MongoDB connected');}
async function ensureAdminUser(){const email=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),password=String(process.env.ADMIN_PASSWORD||'');if(!email||!password)return;if(password.length<8)throw new Error('ADMIN_PASSWORD must be at least 8 characters.');const passwordHash=await bcrypt.hash(password,12);const existing=await User.findOne({email});if(!existing)await User.create({name:'Administrator',email,university:'',passwordHash,role:'admin'});else if(existing.role!=='admin'){existing.role='admin';existing.passwordHash=passwordHash;await existing.save();}}
export{app};
async function start(){await connectDatabase();app.listen(PORT,()=>console.log(`Professor Review API with Sidd AI running on port ${PORT}`));}
if(!process.env.VERCEL)start().catch(e=>{console.error('Failed to start server:',e);process.exit(1);});
